[package]
name = "t9"
entry = "src/app/app_main.zi"
module_roots = ["src", "src/app", "src/terminal_pane", "tests", "benchmarks"]

[toolchain]
git = "https://github.com/ziranlang/ziran.git"
ref = "master"

[dependencies.kryon]
git = "https://github.com/kryonlabs/kryon.git"
ref = "master"

[exports]
app_host = "src/app/app_host.zi"
terminal = "src/terminal.zi"
terminal_pane_widget = "src/terminal_pane/terminal_pane_widget.zi"
